# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('m', '\u7537'), ('w', '\u5973')], max_length=10, verbose_name='\u6027\u522b')),
            ],
            options={
                'db_table': 'music_album',
            },
        ),
    ]
