# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
