# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruduct', '0003_auto_20191204_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('id',)},
        ),
    ]
