# Generated by Django 3.0 on 2019-12-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruduct', '0004_auto_20191213_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoples', models.CharField(max_length=150)),
                ('card', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techer_name', models.CharField(max_length=150)),
                ('stu', models.ManyToManyField(to='pruduct.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kechengming', models.CharField(max_length=150)),
                ('shichang', models.CharField(max_length=150)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pruduct.Student')),
            ],
        ),
    ]
