# Generated by Django 3.0 on 2019-12-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruduct', '0005_people_student_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='pruduct.Student'),
        ),
    ]
